name: Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_api:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das depedências do Projeto
          pip install -r requirements.txt

      - name: Run Robot Framework Tests
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        run: |
          echo Executando os testes de API do Robot
          robot --name "API Tests" --outputdir results tests || true
    
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report-api
          path: results/

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - test_api
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://marilliadantas.github.io/robot-academy/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report-api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4